<?php
declare(strict_types=1);

namespace Test;

use App\Entity\Link;
use App\Enum\LinkPropertyEnum;
use App\Enum\LinkTypeEnum;
use App\Enum\ProviderEnum;
use App\Service\LinkHelpers;
use PHPUnit\Framework\TestCase;

final class LinkHelpersTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test(): void
    {
        $link = $this->createMock(Link::class);
        $link->method('getType')
            ->will($this->onConsecutiveCalls(LinkTypeEnum::TYPE_VIDEO,
                                                   LinkTypeEnum::TYPE_IMAGE));


        $defaultProperties = [LinkPropertyEnum::PROPERTY_WIDTH, LinkPropertyEnum::PROPERTY_HEIGHT];

        $expectedLinkProperties[LinkTypeEnum::TYPE_IMAGE] = $defaultProperties;
        $expectedLinkProperties[LinkTypeEnum::TYPE_VIDEO] = [...$defaultProperties, LinkPropertyEnum::PROPERTY_DURATION];

        $this->assertEquals($expectedLinkProperties[LinkTypeEnum::TYPE_VIDEO], LinkHelpers::getPropertiesList($link));
        $this->assertEquals($expectedLinkProperties[LinkTypeEnum::TYPE_IMAGE],LinkHelpers::getPropertiesList($link));

        $url['video'] = 'https://vimeo.com/26020014';
        $url['image'] = 'https://www.flickr.com/photos/danielcheong/51920514592/in/explore-2022-03-07/';

        $this->assertTrue(LinkHelpers::isValid($url['image']),'LinkHelpers::isValid function is broken');

        $existingProvider = ProviderEnum::PROVIDER_FLICKR;
        $unknownProvider = 'foo.bar';

        $this->assertSame($existingProvider,LinkHelpers::extractProvider($existingProvider));
        $this->assertNull(LinkHelpers::extractProvider($unknownProvider));
    }

}